source "https://rubygems.org"

gem 'rspec'
gem 'nokogiri'
gem 'pry'
gem 'css_parser'
gem 'did_you_mean', '~> 1.4'
gem 'etc', '~> 1.1'
gem 'fileutils', '~> 1.4', '>= 1.4.1'
gem 'strscan', '~> 1.0', '>= 1.0.3'
gem 'zlib', '~> 1.1'
gem 'stringio', '~> 0.0.2'
gem 'date', '~> 2.0'
gem 'openssl', '~> 2.1', '>= 2.1.2'
gem 'forwardable', '~> 1.2'